[versions]
agp = "8.9.1"
audiowaveProgressbar = "0.9.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
androidMail = "1.6.7"
androidActivation = "1.6.7"
recyclerview = "1.4.0"
roomRuntime = "2.7.0"
roomCompiler = "2.7.0"
lifecycleExtensions = "2.2.0"
updateChecker = "1.2"
workRuntime = "2.10.0"
core = "1.16.0"
legacySupportCoreUtils = "1.0.0"
gson = "2.13.1"
cameraCore = "1.5.0-alpha06"
cameraCamera2 = "1.5.0-alpha06"
cameraLifecycle = "1.5.0-alpha06"
cameraView = "1.5.0-alpha06"
glide = "5.0.0-rc01"
lottie = "6.6.2"

[libraries]
audiowave-progressbar = { module = "com.github.alxrm:audiowave-progressbar", version.ref = "audiowaveProgressbar" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
android-mail = { group = "com.sun.mail", name = "android-mail", version.ref = "androidMail" }
android-activation = { group = "com.sun.mail", name = "android-activation", version.ref = "androidActivation" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycleExtensions" }
update-checker = { module = "com.github.lenier522:Update-Checker", version.ref = "updateChecker" }
work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "workRuntime" }
core = { group = "androidx.core", name = "core", version.ref = "core" }
legacy-support-core-utils = { group = "androidx.legacy", name = "legacy-support-core-utils", version.ref = "legacySupportCoreUtils" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraCamera2" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

